version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - "5000:5000"
    volumes:
      - ./flask/code:/code
      - ./images:/code/static/images
      - ./css:/code/static/css
      - ./js:/code/static/js
      - ./command:/code/command
      - ./.moirai:/.moirai
