version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - "5000:5000"
    volumes:
      - ./flask/code:/code
      - ./command:/command
      - ./.moirai:/.moirai