version: "3.9"
services:
  nginx:
    hostname: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-compose/nginx/log:/var/log/nginx
      - ./docker-compose/nginx/public:/usr/share/nginx/html
      - ./command:/usr/share/nginx/html/command
      - ./input:/usr/share/nginx/html/input
  webhookd:
    hostname: webhookd
    build:
      context: ./docker-compose/webhookd
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8081:8080"
    environment:
      - WHD_SCRIPTS=/scripts
    volumes:
      - ./docker-compose/webhookd/scripts:/scripts
      - ./dag.pl:/usr/bin/dag.pl
      - ./moirai2.pl:/usr/bin/moirai2.pl